### ISSUE TITLE
页面初始边框高度太大，建议初始高度用添加公众号高度的2倍加上行距

### ISSUE THREAD

**Issue by big-rui** [mazong1123/wbl#116]
![image](https://cloud.githubusercontent.com/assets/13230396/9190282/01b2ce12-4026-11e5-8dc5-c2e99cd1d544.png)

**Comment by mazong1123** [comment]
页面高度根据内容撑开，并且只有一页的情况下没有翻页的栏目

**Comment by big-rui** [comment]
已修复成两倍高度
