### ISSUE TITLE
退出提示框的退出按钮和继续答题按钮位置交换，且继续答题按钮应更为醒目

### ISSUE THREAD

**Issue by mazong1123** [mazong1123/wbl#18]
![9oojte7y siw mw yx149d4](https://cloud.githubusercontent.com/assets/4554154/8570582/f1e58790-25b3-11e5-9db1-2c3bceb70ce1.jpg)

**Comment by mysunnytime** [comment]
按钮顺序和颜色
文字修改

**Comment by mysunnytime** [comment]
更改了高度，按钮顺序交换了，文字修改了，退出按钮弱化了。
按钮弱化方式为，在alert dialog show的时候（按钮生成时），给退出的span的父元素button添加弱化class：general-alert-dialog-unemphasized-btn
