### ISSUE TITLE
特易聚网站优化集合

### ISSUE THREAD

**Issue by mazong1123** [mazong1123/wbl#75]
1. favicon 要加上
2. head里面要加seo信息

mazong1123 2015-07-17 22:46:11
3. 点logo应该返回首页

mazong1123 2015-07-17 22:53:09
这句话是个什么。。

mazong1123 2015-07-17 22:53:30
这3句话都得改

mazong1123 2015-07-17 22:54:07
![Uploading image.png…]()

mazong1123 2015-07-17 22:54:12
卷-〉券

mazong1123 2015-07-17 22:54:26

![Uploading image.png…]()

mazong1123 2015-07-17 22:54:32
空格是故意的吗？
![Uploading image.png…]()
点击你必须到“产品介绍”字上面才跳转

mazong1123 2015-07-17 23:05:36
在红线和产品介绍之间点击居然不跳转

**Comment by mysunnytime** [comment]
除4外其他已修复。等待修改的文案

**Comment by mysunnytime** [comment]
已修复。
